#define TOKEN_SEMICOLON                        1
#define TOKEN_CREATE                           2
#define TOKEN_TABLE                            3
#define TOKEN_LP                               4
#define TOKEN_RP                               5
#define TOKEN_IF                               6
#define TOKEN_NOT                              7
#define TOKEN_EXISTS                           8
#define TOKEN_COMMA                            9
#define TOKEN_INTEGER                         10
#define TOKEN_INT_TYPE                        11
#define TOKEN_CHAR_TYPE                       12
#define TOKEN_FLOAT_TYPE                      13
#define TOKEN_PRIMARY                         14
#define TOKEN_KEY                             15
#define TOKEN_UNIQUE                          16
#define TOKEN_STRING                          17
#define TOKEN_ID                              18
#define TOKEN_DROP                            19
#define TOKEN_OR                              20
#define TOKEN_AND                             21
#define TOKEN_IS                              22
#define TOKEN_NE                              23
#define TOKEN_EQ                              24
#define TOKEN_BETWEEN                         25
#define TOKEN_GT                              26
#define TOKEN_LE                              27
#define TOKEN_LT                              28
#define TOKEN_GE                              29
