// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/FriendListMessage.proto

package proto;

public final class FriendListMessageProto {
  private FriendListMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FriendListMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.FriendListMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.FriendListMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .proto.FriendListMessage.Type type = 1;</code>
     */
    proto.FriendListMessageProto.FriendListMessage.Type getType();

    /**
     * <code>optional int64 account = 2;</code>
     */
    boolean hasAccount();
    /**
     * <code>optional int64 account = 2;</code>
     */
    long getAccount();

    /**
     * <code>optional string nickname = 3;</code>
     */
    boolean hasNickname();
    /**
     * <code>optional string nickname = 3;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 3;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional bytes avatar = 4;</code>
     */
    boolean hasAvatar();
    /**
     * <code>optional bytes avatar = 4;</code>
     */
    com.google.protobuf.ByteString getAvatar();
  }
  /**
   * Protobuf type {@code proto.FriendListMessage}
   */
  public  static final class FriendListMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.FriendListMessage)
      FriendListMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FriendListMessage.newBuilder() to construct.
    private FriendListMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FriendListMessage() {
      type_ = 0;
      account_ = 0L;
      nickname_ = "";
      avatar_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FriendListMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.FriendListMessageProto.FriendListMessage.Type value = proto.FriendListMessageProto.FriendListMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              account_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              nickname_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              avatar_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.FriendListMessageProto.internal_static_proto_FriendListMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.FriendListMessageProto.internal_static_proto_FriendListMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FriendListMessageProto.FriendListMessage.class, proto.FriendListMessageProto.FriendListMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.FriendListMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SELF = 0;</code>
       */
      SELF(0),
      /**
       * <code>FRIEND = 1;</code>
       */
      FRIEND(1),
      /**
       * <code>GROUP = 2;</code>
       */
      GROUP(2),
      /**
       * <code>REQUIRE = 3;</code>
       */
      REQUIRE(3),
      /**
       * <code>FRIENDSEARCH = 4;</code>
       */
      FRIENDSEARCH(4),
      /**
       * <code>GROUPSEARCH = 5;</code>
       */
      GROUPSEARCH(5),
      /**
       * <code>ADDFRIEND = 6;</code>
       */
      ADDFRIEND(6),
      /**
       * <code>ADDGROUP = 7;</code>
       */
      ADDGROUP(7),
      ;

      /**
       * <code>SELF = 0;</code>
       */
      public static final int SELF_VALUE = 0;
      /**
       * <code>FRIEND = 1;</code>
       */
      public static final int FRIEND_VALUE = 1;
      /**
       * <code>GROUP = 2;</code>
       */
      public static final int GROUP_VALUE = 2;
      /**
       * <code>REQUIRE = 3;</code>
       */
      public static final int REQUIRE_VALUE = 3;
      /**
       * <code>FRIENDSEARCH = 4;</code>
       */
      public static final int FRIENDSEARCH_VALUE = 4;
      /**
       * <code>GROUPSEARCH = 5;</code>
       */
      public static final int GROUPSEARCH_VALUE = 5;
      /**
       * <code>ADDFRIEND = 6;</code>
       */
      public static final int ADDFRIEND_VALUE = 6;
      /**
       * <code>ADDGROUP = 7;</code>
       */
      public static final int ADDGROUP_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return SELF;
          case 1: return FRIEND;
          case 2: return GROUP;
          case 3: return REQUIRE;
          case 4: return FRIENDSEARCH;
          case 5: return GROUPSEARCH;
          case 6: return ADDFRIEND;
          case 7: return ADDGROUP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.FriendListMessageProto.FriendListMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.FriendListMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .proto.FriendListMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.FriendListMessage.Type type = 1;</code>
     */
    public proto.FriendListMessageProto.FriendListMessage.Type getType() {
      proto.FriendListMessageProto.FriendListMessage.Type result = proto.FriendListMessageProto.FriendListMessage.Type.valueOf(type_);
      return result == null ? proto.FriendListMessageProto.FriendListMessage.Type.SELF : result;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private long account_;
    /**
     * <code>optional int64 account = 2;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 account = 2;</code>
     */
    public long getAccount() {
      return account_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 3;</code>
     */
    public boolean hasNickname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString avatar_;
    /**
     * <code>optional bytes avatar = 4;</code>
     */
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes avatar = 4;</code>
     */
    public com.google.protobuf.ByteString getAvatar() {
      return avatar_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickname_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, avatar_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickname_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, avatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.FriendListMessageProto.FriendListMessage)) {
        return super.equals(obj);
      }
      proto.FriendListMessageProto.FriendListMessage other = (proto.FriendListMessageProto.FriendListMessage) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasAccount() == other.hasAccount());
      if (hasAccount()) {
        result = result && (getAccount()
            == other.getAccount());
      }
      result = result && (hasNickname() == other.hasNickname());
      if (hasNickname()) {
        result = result && getNickname()
            .equals(other.getNickname());
      }
      result = result && (hasAvatar() == other.hasAvatar());
      if (hasAvatar()) {
        result = result && getAvatar()
            .equals(other.getAvatar());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasAccount()) {
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAccount());
      }
      if (hasNickname()) {
        hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
        hash = (53 * hash) + getNickname().hashCode();
      }
      if (hasAvatar()) {
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatar().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.FriendListMessageProto.FriendListMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.FriendListMessageProto.FriendListMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.FriendListMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.FriendListMessage)
        proto.FriendListMessageProto.FriendListMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.FriendListMessageProto.internal_static_proto_FriendListMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.FriendListMessageProto.internal_static_proto_FriendListMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.FriendListMessageProto.FriendListMessage.class, proto.FriendListMessageProto.FriendListMessage.Builder.class);
      }

      // Construct using proto.FriendListMessageProto.FriendListMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        nickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        avatar_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.FriendListMessageProto.internal_static_proto_FriendListMessage_descriptor;
      }

      public proto.FriendListMessageProto.FriendListMessage getDefaultInstanceForType() {
        return proto.FriendListMessageProto.FriendListMessage.getDefaultInstance();
      }

      public proto.FriendListMessageProto.FriendListMessage build() {
        proto.FriendListMessageProto.FriendListMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.FriendListMessageProto.FriendListMessage buildPartial() {
        proto.FriendListMessageProto.FriendListMessage result = new proto.FriendListMessageProto.FriendListMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nickname_ = nickname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.avatar_ = avatar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.FriendListMessageProto.FriendListMessage) {
          return mergeFrom((proto.FriendListMessageProto.FriendListMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.FriendListMessageProto.FriendListMessage other) {
        if (other == proto.FriendListMessageProto.FriendListMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasNickname()) {
          bitField0_ |= 0x00000004;
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.hasAvatar()) {
          setAvatar(other.getAvatar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.FriendListMessageProto.FriendListMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.FriendListMessageProto.FriendListMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .proto.FriendListMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .proto.FriendListMessage.Type type = 1;</code>
       */
      public proto.FriendListMessageProto.FriendListMessage.Type getType() {
        proto.FriendListMessageProto.FriendListMessage.Type result = proto.FriendListMessageProto.FriendListMessage.Type.valueOf(type_);
        return result == null ? proto.FriendListMessageProto.FriendListMessage.Type.SELF : result;
      }
      /**
       * <code>optional .proto.FriendListMessage.Type type = 1;</code>
       */
      public Builder setType(proto.FriendListMessageProto.FriendListMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.FriendListMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private long account_ ;
      /**
       * <code>optional int64 account = 2;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 account = 2;</code>
       */
      public long getAccount() {
        return account_;
      }
      /**
       * <code>optional int64 account = 2;</code>
       */
      public Builder setAccount(long value) {
        bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 account = 2;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 3;</code>
       */
      public boolean hasNickname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public Builder clearNickname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 3;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nickname_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString avatar_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes avatar = 4;</code>
       */
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes avatar = 4;</code>
       */
      public com.google.protobuf.ByteString getAvatar() {
        return avatar_;
      }
      /**
       * <code>optional bytes avatar = 4;</code>
       */
      public Builder setAvatar(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes avatar = 4;</code>
       */
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00000008);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.FriendListMessage)
    }

    // @@protoc_insertion_point(class_scope:proto.FriendListMessage)
    private static final proto.FriendListMessageProto.FriendListMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.FriendListMessageProto.FriendListMessage();
    }

    public static proto.FriendListMessageProto.FriendListMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FriendListMessage>
        PARSER = new com.google.protobuf.AbstractParser<FriendListMessage>() {
      public FriendListMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FriendListMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FriendListMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FriendListMessage> getParserForType() {
      return PARSER;
    }

    public proto.FriendListMessageProto.FriendListMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FriendListMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FriendListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035proto/FriendListMessage.proto\022\005proto\"\351" +
      "\001\n\021FriendListMessage\022+\n\004type\030\001 \001(\0162\035.pro" +
      "to.FriendListMessage.Type\022\017\n\007account\030\002 \001" +
      "(\003\022\020\n\010nickname\030\003 \001(\t\022\016\n\006avatar\030\004 \001(\014\"t\n\004" +
      "Type\022\010\n\004SELF\020\000\022\n\n\006FRIEND\020\001\022\t\n\005GROUP\020\002\022\013\n" +
      "\007REQUIRE\020\003\022\020\n\014FRIENDSEARCH\020\004\022\017\n\013GROUPSEA" +
      "RCH\020\005\022\r\n\tADDFRIEND\020\006\022\014\n\010ADDGROUP\020\007B\030B\026Fr" +
      "iendListMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_FriendListMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_FriendListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FriendListMessage_descriptor,
        new java.lang.String[] { "Type", "Account", "Nickname", "Avatar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
