// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Message.proto

package proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    proto.MessageProto.Message.Type getType();

    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    boolean hasChatMessage();
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    proto.ChatMessageProto.ChatMessage getChatMessage();
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder();

    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    boolean hasLoginMessage();
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    proto.LoginMessageProto.LoginMessage getLoginMessage();
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    proto.LoginMessageProto.LoginMessageOrBuilder getLoginMessageOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.MessageProto.Message.Type value = proto.MessageProto.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              proto.ChatMessageProto.ChatMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = chatMessage_.toBuilder();
              }
              chatMessage_ = input.readMessage(proto.ChatMessageProto.ChatMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatMessage_);
                chatMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              proto.LoginMessageProto.LoginMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = loginMessage_.toBuilder();
              }
              loginMessage_ = input.readMessage(proto.LoginMessageProto.LoginMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginMessage_);
                loginMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.MessageProto.internal_static_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.MessageProto.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.MessageProto.Message.class, proto.MessageProto.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.Message.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LoginMessage = 1;</code>
       */
      LoginMessage(1),
      /**
       * <code>ChatMessage = 2;</code>
       */
      ChatMessage(2),
      ;

      /**
       * <code>LoginMessage = 1;</code>
       */
      public static final int LoginMessage_VALUE = 1;
      /**
       * <code>ChatMessage = 2;</code>
       */
      public static final int ChatMessage_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 1: return LoginMessage;
          case 2: return ChatMessage;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.MessageProto.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Message.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    public proto.MessageProto.Message.Type getType() {
      proto.MessageProto.Message.Type result = proto.MessageProto.Message.Type.valueOf(type_);
      return result == null ? proto.MessageProto.Message.Type.LoginMessage : result;
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 2;
    private proto.ChatMessageProto.ChatMessage chatMessage_;
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    public boolean hasChatMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    public proto.ChatMessageProto.ChatMessage getChatMessage() {
      return chatMessage_ == null ? proto.ChatMessageProto.ChatMessage.getDefaultInstance() : chatMessage_;
    }
    /**
     * <code>optional .proto.ChatMessage chatMessage = 2;</code>
     */
    public proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder() {
      return chatMessage_ == null ? proto.ChatMessageProto.ChatMessage.getDefaultInstance() : chatMessage_;
    }

    public static final int LOGINMESSAGE_FIELD_NUMBER = 3;
    private proto.LoginMessageProto.LoginMessage loginMessage_;
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    public boolean hasLoginMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    public proto.LoginMessageProto.LoginMessage getLoginMessage() {
      return loginMessage_ == null ? proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
    }
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    public proto.LoginMessageProto.LoginMessageOrBuilder getLoginMessageOrBuilder() {
      return loginMessage_ == null ? proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasChatMessage()) {
        if (!getChatMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getChatMessage());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getLoginMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getChatMessage());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.MessageProto.Message)) {
        return super.equals(obj);
      }
      proto.MessageProto.Message other = (proto.MessageProto.Message) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasChatMessage() == other.hasChatMessage());
      if (hasChatMessage()) {
        result = result && getChatMessage()
            .equals(other.getChatMessage());
      }
      result = result && (hasLoginMessage() == other.hasLoginMessage());
      if (hasLoginMessage()) {
        result = result && getLoginMessage()
            .equals(other.getLoginMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasChatMessage()) {
        hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChatMessage().hashCode();
      }
      if (hasLoginMessage()) {
        hash = (37 * hash) + LOGINMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLoginMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        proto.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.MessageProto.internal_static_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.MessageProto.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.MessageProto.Message.class, proto.MessageProto.Message.Builder.class);
      }

      // Construct using proto.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChatMessageFieldBuilder();
          getLoginMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (loginMessageBuilder_ == null) {
          loginMessage_ = null;
        } else {
          loginMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.MessageProto.internal_static_proto_Message_descriptor;
      }

      public proto.MessageProto.Message getDefaultInstanceForType() {
        return proto.MessageProto.Message.getDefaultInstance();
      }

      public proto.MessageProto.Message build() {
        proto.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.MessageProto.Message buildPartial() {
        proto.MessageProto.Message result = new proto.MessageProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (chatMessageBuilder_ == null) {
          result.chatMessage_ = chatMessage_;
        } else {
          result.chatMessage_ = chatMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (loginMessageBuilder_ == null) {
          result.loginMessage_ = loginMessage_;
        } else {
          result.loginMessage_ = loginMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.MessageProto.Message) {
          return mergeFrom((proto.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.MessageProto.Message other) {
        if (other == proto.MessageProto.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasChatMessage()) {
          mergeChatMessage(other.getChatMessage());
        }
        if (other.hasLoginMessage()) {
          mergeLoginMessage(other.getLoginMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (hasChatMessage()) {
          if (!getChatMessage().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public proto.MessageProto.Message.Type getType() {
        proto.MessageProto.Message.Type result = proto.MessageProto.Message.Type.valueOf(type_);
        return result == null ? proto.MessageProto.Message.Type.LoginMessage : result;
      }
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public Builder setType(proto.MessageProto.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private proto.ChatMessageProto.ChatMessage chatMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder> chatMessageBuilder_;
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public boolean hasChatMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage getChatMessage() {
        if (chatMessageBuilder_ == null) {
          return chatMessage_ == null ? proto.ChatMessageProto.ChatMessage.getDefaultInstance() : chatMessage_;
        } else {
          return chatMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder setChatMessage(proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatMessage_ = value;
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder setChatMessage(
          proto.ChatMessageProto.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = builderForValue.build();
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder mergeChatMessage(proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              chatMessage_ != null &&
              chatMessage_ != proto.ChatMessageProto.ChatMessage.getDefaultInstance()) {
            chatMessage_ =
              proto.ChatMessageProto.ChatMessage.newBuilder(chatMessage_).mergeFrom(value).buildPartial();
          } else {
            chatMessage_ = value;
          }
          onChanged();
        } else {
          chatMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder clearChatMessage() {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = null;
          onChanged();
        } else {
          chatMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage.Builder getChatMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getChatMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder() {
        if (chatMessageBuilder_ != null) {
          return chatMessageBuilder_.getMessageOrBuilder();
        } else {
          return chatMessage_ == null ?
              proto.ChatMessageProto.ChatMessage.getDefaultInstance() : chatMessage_;
        }
      }
      /**
       * <code>optional .proto.ChatMessage chatMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder> 
          getChatMessageFieldBuilder() {
        if (chatMessageBuilder_ == null) {
          chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder>(
                  getChatMessage(),
                  getParentForChildren(),
                  isClean());
          chatMessage_ = null;
        }
        return chatMessageBuilder_;
      }

      private proto.LoginMessageProto.LoginMessage loginMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.LoginMessageProto.LoginMessage, proto.LoginMessageProto.LoginMessage.Builder, proto.LoginMessageProto.LoginMessageOrBuilder> loginMessageBuilder_;
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public boolean hasLoginMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public proto.LoginMessageProto.LoginMessage getLoginMessage() {
        if (loginMessageBuilder_ == null) {
          return loginMessage_ == null ? proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
        } else {
          return loginMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder setLoginMessage(proto.LoginMessageProto.LoginMessage value) {
        if (loginMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginMessage_ = value;
          onChanged();
        } else {
          loginMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder setLoginMessage(
          proto.LoginMessageProto.LoginMessage.Builder builderForValue) {
        if (loginMessageBuilder_ == null) {
          loginMessage_ = builderForValue.build();
          onChanged();
        } else {
          loginMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder mergeLoginMessage(proto.LoginMessageProto.LoginMessage value) {
        if (loginMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              loginMessage_ != null &&
              loginMessage_ != proto.LoginMessageProto.LoginMessage.getDefaultInstance()) {
            loginMessage_ =
              proto.LoginMessageProto.LoginMessage.newBuilder(loginMessage_).mergeFrom(value).buildPartial();
          } else {
            loginMessage_ = value;
          }
          onChanged();
        } else {
          loginMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder clearLoginMessage() {
        if (loginMessageBuilder_ == null) {
          loginMessage_ = null;
          onChanged();
        } else {
          loginMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public proto.LoginMessageProto.LoginMessage.Builder getLoginMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLoginMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public proto.LoginMessageProto.LoginMessageOrBuilder getLoginMessageOrBuilder() {
        if (loginMessageBuilder_ != null) {
          return loginMessageBuilder_.getMessageOrBuilder();
        } else {
          return loginMessage_ == null ?
              proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
        }
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.LoginMessageProto.LoginMessage, proto.LoginMessageProto.LoginMessage.Builder, proto.LoginMessageProto.LoginMessageOrBuilder> 
          getLoginMessageFieldBuilder() {
        if (loginMessageBuilder_ == null) {
          loginMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.LoginMessageProto.LoginMessage, proto.LoginMessageProto.LoginMessage.Builder, proto.LoginMessageProto.LoginMessageOrBuilder>(
                  getLoginMessage(),
                  getParentForChildren(),
                  isClean());
          loginMessage_ = null;
        }
        return loginMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
    private static final proto.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.MessageProto.Message();
    }

    public static proto.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public proto.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/Message.proto\022\005proto\032\027proto/Chat" +
      "Message.proto\032\030proto/LoginMessage.proto\"" +
      "\253\001\n\007Message\022!\n\004type\030\001 \002(\0162\023.proto.Messag" +
      "e.Type\022\'\n\013chatMessage\030\002 \001(\0132\022.proto.Chat" +
      "Message\022)\n\014loginMessage\030\003 \001(\0132\023.proto.Lo" +
      "ginMessage\")\n\004Type\022\020\n\014LoginMessage\020\001\022\017\n\013" +
      "ChatMessage\020\002B\016B\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.ChatMessageProto.getDescriptor(),
          proto.LoginMessageProto.getDescriptor(),
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "Type", "ChatMessage", "LoginMessage", });
    proto.ChatMessageProto.getDescriptor();
    proto.LoginMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
