// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Message.proto

package proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    proto.MessageProto.Message.Type getType();

    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    java.util.List<proto.ChatMessageProto.ChatMessage> 
        getChatMessageList();
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    proto.ChatMessageProto.ChatMessage getChatMessage(int index);
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    int getChatMessageCount();
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    java.util.List<? extends proto.ChatMessageProto.ChatMessageOrBuilder> 
        getChatMessageOrBuilderList();
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder(
        int index);

    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    boolean hasLoginMessage();
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    proto.LoginMessageProto.LoginMessage getLoginMessage();
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    proto.LoginMessageProto.LoginMessageOrBuilder getLoginMessageOrBuilder();

    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    java.util.List<proto.FriendListMessageProto.FriendListMessage> 
        getFriendListMesageList();
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    proto.FriendListMessageProto.FriendListMessage getFriendListMesage(int index);
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    int getFriendListMesageCount();
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    java.util.List<? extends proto.FriendListMessageProto.FriendListMessageOrBuilder> 
        getFriendListMesageOrBuilderList();
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    proto.FriendListMessageProto.FriendListMessageOrBuilder getFriendListMesageOrBuilder(
        int index);

    /**
     * <code>optional string errorMessage = 5;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 5;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 5;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      chatMessage_ = java.util.Collections.emptyList();
      friendListMesage_ = java.util.Collections.emptyList();
      errorMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.MessageProto.Message.Type value = proto.MessageProto.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                chatMessage_ = new java.util.ArrayList<proto.ChatMessageProto.ChatMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              chatMessage_.add(
                  input.readMessage(proto.ChatMessageProto.ChatMessage.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              proto.LoginMessageProto.LoginMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = loginMessage_.toBuilder();
              }
              loginMessage_ = input.readMessage(proto.LoginMessageProto.LoginMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginMessage_);
                loginMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                friendListMesage_ = new java.util.ArrayList<proto.FriendListMessageProto.FriendListMessage>();
                mutable_bitField0_ |= 0x00000008;
              }
              friendListMesage_.add(
                  input.readMessage(proto.FriendListMessageProto.FriendListMessage.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errorMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          chatMessage_ = java.util.Collections.unmodifiableList(chatMessage_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          friendListMesage_ = java.util.Collections.unmodifiableList(friendListMesage_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.MessageProto.internal_static_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.MessageProto.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.MessageProto.Message.class, proto.MessageProto.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.Message.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LoginMessage = 0;</code>
       */
      LoginMessage(0),
      /**
       * <code>ChatMessage = 1;</code>
       */
      ChatMessage(1),
      /**
       * <code>FriendListMessage = 2;</code>
       */
      FriendListMessage(2),
      /**
       * <code>ErrorMessage = 3;</code>
       */
      ErrorMessage(3),
      ;

      /**
       * <code>LoginMessage = 0;</code>
       */
      public static final int LoginMessage_VALUE = 0;
      /**
       * <code>ChatMessage = 1;</code>
       */
      public static final int ChatMessage_VALUE = 1;
      /**
       * <code>FriendListMessage = 2;</code>
       */
      public static final int FriendListMessage_VALUE = 2;
      /**
       * <code>ErrorMessage = 3;</code>
       */
      public static final int ErrorMessage_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return LoginMessage;
          case 1: return ChatMessage;
          case 2: return FriendListMessage;
          case 3: return ErrorMessage;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.MessageProto.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Message.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .proto.Message.Type type = 1;</code>
     */
    public proto.MessageProto.Message.Type getType() {
      proto.MessageProto.Message.Type result = proto.MessageProto.Message.Type.valueOf(type_);
      return result == null ? proto.MessageProto.Message.Type.LoginMessage : result;
    }

    public static final int CHATMESSAGE_FIELD_NUMBER = 2;
    private java.util.List<proto.ChatMessageProto.ChatMessage> chatMessage_;
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    public java.util.List<proto.ChatMessageProto.ChatMessage> getChatMessageList() {
      return chatMessage_;
    }
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    public java.util.List<? extends proto.ChatMessageProto.ChatMessageOrBuilder> 
        getChatMessageOrBuilderList() {
      return chatMessage_;
    }
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    public int getChatMessageCount() {
      return chatMessage_.size();
    }
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    public proto.ChatMessageProto.ChatMessage getChatMessage(int index) {
      return chatMessage_.get(index);
    }
    /**
     * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
     */
    public proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder(
        int index) {
      return chatMessage_.get(index);
    }

    public static final int LOGINMESSAGE_FIELD_NUMBER = 3;
    private proto.LoginMessageProto.LoginMessage loginMessage_;
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    public boolean hasLoginMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    public proto.LoginMessageProto.LoginMessage getLoginMessage() {
      return loginMessage_ == null ? proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
    }
    /**
     * <code>optional .proto.LoginMessage loginMessage = 3;</code>
     */
    public proto.LoginMessageProto.LoginMessageOrBuilder getLoginMessageOrBuilder() {
      return loginMessage_ == null ? proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
    }

    public static final int FRIENDLISTMESAGE_FIELD_NUMBER = 4;
    private java.util.List<proto.FriendListMessageProto.FriendListMessage> friendListMesage_;
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    public java.util.List<proto.FriendListMessageProto.FriendListMessage> getFriendListMesageList() {
      return friendListMesage_;
    }
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    public java.util.List<? extends proto.FriendListMessageProto.FriendListMessageOrBuilder> 
        getFriendListMesageOrBuilderList() {
      return friendListMesage_;
    }
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    public int getFriendListMesageCount() {
      return friendListMesage_.size();
    }
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    public proto.FriendListMessageProto.FriendListMessage getFriendListMesage(int index) {
      return friendListMesage_.get(index);
    }
    /**
     * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
     */
    public proto.FriendListMessageProto.FriendListMessageOrBuilder getFriendListMesageOrBuilder(
        int index) {
      return friendListMesage_.get(index);
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 5;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string errorMessage = 5;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 5;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getChatMessageCount(); i++) {
        if (!getChatMessage(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < chatMessage_.size(); i++) {
        output.writeMessage(2, chatMessage_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, getLoginMessage());
      }
      for (int i = 0; i < friendListMesage_.size(); i++) {
        output.writeMessage(4, friendListMesage_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, errorMessage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < chatMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, chatMessage_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginMessage());
      }
      for (int i = 0; i < friendListMesage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, friendListMesage_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, errorMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.MessageProto.Message)) {
        return super.equals(obj);
      }
      proto.MessageProto.Message other = (proto.MessageProto.Message) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && getChatMessageList()
          .equals(other.getChatMessageList());
      result = result && (hasLoginMessage() == other.hasLoginMessage());
      if (hasLoginMessage()) {
        result = result && getLoginMessage()
            .equals(other.getLoginMessage());
      }
      result = result && getFriendListMesageList()
          .equals(other.getFriendListMesageList());
      result = result && (hasErrorMessage() == other.hasErrorMessage());
      if (hasErrorMessage()) {
        result = result && getErrorMessage()
            .equals(other.getErrorMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (getChatMessageCount() > 0) {
        hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getChatMessageList().hashCode();
      }
      if (hasLoginMessage()) {
        hash = (37 * hash) + LOGINMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLoginMessage().hashCode();
      }
      if (getFriendListMesageCount() > 0) {
        hash = (37 * hash) + FRIENDLISTMESAGE_FIELD_NUMBER;
        hash = (53 * hash) + getFriendListMesageList().hashCode();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        proto.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.MessageProto.internal_static_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.MessageProto.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.MessageProto.Message.class, proto.MessageProto.Message.Builder.class);
      }

      // Construct using proto.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChatMessageFieldBuilder();
          getLoginMessageFieldBuilder();
          getFriendListMesageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (chatMessageBuilder_ == null) {
          chatMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          chatMessageBuilder_.clear();
        }
        if (loginMessageBuilder_ == null) {
          loginMessage_ = null;
        } else {
          loginMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (friendListMesageBuilder_ == null) {
          friendListMesage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          friendListMesageBuilder_.clear();
        }
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.MessageProto.internal_static_proto_Message_descriptor;
      }

      public proto.MessageProto.Message getDefaultInstanceForType() {
        return proto.MessageProto.Message.getDefaultInstance();
      }

      public proto.MessageProto.Message build() {
        proto.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.MessageProto.Message buildPartial() {
        proto.MessageProto.Message result = new proto.MessageProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (chatMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            chatMessage_ = java.util.Collections.unmodifiableList(chatMessage_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.chatMessage_ = chatMessage_;
        } else {
          result.chatMessage_ = chatMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (loginMessageBuilder_ == null) {
          result.loginMessage_ = loginMessage_;
        } else {
          result.loginMessage_ = loginMessageBuilder_.build();
        }
        if (friendListMesageBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            friendListMesage_ = java.util.Collections.unmodifiableList(friendListMesage_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.friendListMesage_ = friendListMesage_;
        } else {
          result.friendListMesage_ = friendListMesageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.MessageProto.Message) {
          return mergeFrom((proto.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.MessageProto.Message other) {
        if (other == proto.MessageProto.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (chatMessageBuilder_ == null) {
          if (!other.chatMessage_.isEmpty()) {
            if (chatMessage_.isEmpty()) {
              chatMessage_ = other.chatMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureChatMessageIsMutable();
              chatMessage_.addAll(other.chatMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.chatMessage_.isEmpty()) {
            if (chatMessageBuilder_.isEmpty()) {
              chatMessageBuilder_.dispose();
              chatMessageBuilder_ = null;
              chatMessage_ = other.chatMessage_;
              bitField0_ = (bitField0_ & ~0x00000002);
              chatMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChatMessageFieldBuilder() : null;
            } else {
              chatMessageBuilder_.addAllMessages(other.chatMessage_);
            }
          }
        }
        if (other.hasLoginMessage()) {
          mergeLoginMessage(other.getLoginMessage());
        }
        if (friendListMesageBuilder_ == null) {
          if (!other.friendListMesage_.isEmpty()) {
            if (friendListMesage_.isEmpty()) {
              friendListMesage_ = other.friendListMesage_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFriendListMesageIsMutable();
              friendListMesage_.addAll(other.friendListMesage_);
            }
            onChanged();
          }
        } else {
          if (!other.friendListMesage_.isEmpty()) {
            if (friendListMesageBuilder_.isEmpty()) {
              friendListMesageBuilder_.dispose();
              friendListMesageBuilder_ = null;
              friendListMesage_ = other.friendListMesage_;
              bitField0_ = (bitField0_ & ~0x00000008);
              friendListMesageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFriendListMesageFieldBuilder() : null;
            } else {
              friendListMesageBuilder_.addAllMessages(other.friendListMesage_);
            }
          }
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000010;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getChatMessageCount(); i++) {
          if (!getChatMessage(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public proto.MessageProto.Message.Type getType() {
        proto.MessageProto.Message.Type result = proto.MessageProto.Message.Type.valueOf(type_);
        return result == null ? proto.MessageProto.Message.Type.LoginMessage : result;
      }
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public Builder setType(proto.MessageProto.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.Message.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<proto.ChatMessageProto.ChatMessage> chatMessage_ =
        java.util.Collections.emptyList();
      private void ensureChatMessageIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          chatMessage_ = new java.util.ArrayList<proto.ChatMessageProto.ChatMessage>(chatMessage_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder> chatMessageBuilder_;

      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public java.util.List<proto.ChatMessageProto.ChatMessage> getChatMessageList() {
        if (chatMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(chatMessage_);
        } else {
          return chatMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public int getChatMessageCount() {
        if (chatMessageBuilder_ == null) {
          return chatMessage_.size();
        } else {
          return chatMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage getChatMessage(int index) {
        if (chatMessageBuilder_ == null) {
          return chatMessage_.get(index);
        } else {
          return chatMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder setChatMessage(
          int index, proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatMessageIsMutable();
          chatMessage_.set(index, value);
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder setChatMessage(
          int index, proto.ChatMessageProto.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          ensureChatMessageIsMutable();
          chatMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          chatMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder addChatMessage(proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatMessageIsMutable();
          chatMessage_.add(value);
          onChanged();
        } else {
          chatMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder addChatMessage(
          int index, proto.ChatMessageProto.ChatMessage value) {
        if (chatMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatMessageIsMutable();
          chatMessage_.add(index, value);
          onChanged();
        } else {
          chatMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder addChatMessage(
          proto.ChatMessageProto.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          ensureChatMessageIsMutable();
          chatMessage_.add(builderForValue.build());
          onChanged();
        } else {
          chatMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder addChatMessage(
          int index, proto.ChatMessageProto.ChatMessage.Builder builderForValue) {
        if (chatMessageBuilder_ == null) {
          ensureChatMessageIsMutable();
          chatMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          chatMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder addAllChatMessage(
          java.lang.Iterable<? extends proto.ChatMessageProto.ChatMessage> values) {
        if (chatMessageBuilder_ == null) {
          ensureChatMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, chatMessage_);
          onChanged();
        } else {
          chatMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder clearChatMessage() {
        if (chatMessageBuilder_ == null) {
          chatMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          chatMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public Builder removeChatMessage(int index) {
        if (chatMessageBuilder_ == null) {
          ensureChatMessageIsMutable();
          chatMessage_.remove(index);
          onChanged();
        } else {
          chatMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage.Builder getChatMessageBuilder(
          int index) {
        return getChatMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessageOrBuilder getChatMessageOrBuilder(
          int index) {
        if (chatMessageBuilder_ == null) {
          return chatMessage_.get(index);  } else {
          return chatMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public java.util.List<? extends proto.ChatMessageProto.ChatMessageOrBuilder> 
           getChatMessageOrBuilderList() {
        if (chatMessageBuilder_ != null) {
          return chatMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(chatMessage_);
        }
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage.Builder addChatMessageBuilder() {
        return getChatMessageFieldBuilder().addBuilder(
            proto.ChatMessageProto.ChatMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public proto.ChatMessageProto.ChatMessage.Builder addChatMessageBuilder(
          int index) {
        return getChatMessageFieldBuilder().addBuilder(
            index, proto.ChatMessageProto.ChatMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ChatMessage chatMessage = 2;</code>
       */
      public java.util.List<proto.ChatMessageProto.ChatMessage.Builder> 
           getChatMessageBuilderList() {
        return getChatMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder> 
          getChatMessageFieldBuilder() {
        if (chatMessageBuilder_ == null) {
          chatMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.ChatMessageProto.ChatMessage, proto.ChatMessageProto.ChatMessage.Builder, proto.ChatMessageProto.ChatMessageOrBuilder>(
                  chatMessage_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          chatMessage_ = null;
        }
        return chatMessageBuilder_;
      }

      private proto.LoginMessageProto.LoginMessage loginMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.LoginMessageProto.LoginMessage, proto.LoginMessageProto.LoginMessage.Builder, proto.LoginMessageProto.LoginMessageOrBuilder> loginMessageBuilder_;
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public boolean hasLoginMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public proto.LoginMessageProto.LoginMessage getLoginMessage() {
        if (loginMessageBuilder_ == null) {
          return loginMessage_ == null ? proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
        } else {
          return loginMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder setLoginMessage(proto.LoginMessageProto.LoginMessage value) {
        if (loginMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginMessage_ = value;
          onChanged();
        } else {
          loginMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder setLoginMessage(
          proto.LoginMessageProto.LoginMessage.Builder builderForValue) {
        if (loginMessageBuilder_ == null) {
          loginMessage_ = builderForValue.build();
          onChanged();
        } else {
          loginMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder mergeLoginMessage(proto.LoginMessageProto.LoginMessage value) {
        if (loginMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              loginMessage_ != null &&
              loginMessage_ != proto.LoginMessageProto.LoginMessage.getDefaultInstance()) {
            loginMessage_ =
              proto.LoginMessageProto.LoginMessage.newBuilder(loginMessage_).mergeFrom(value).buildPartial();
          } else {
            loginMessage_ = value;
          }
          onChanged();
        } else {
          loginMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public Builder clearLoginMessage() {
        if (loginMessageBuilder_ == null) {
          loginMessage_ = null;
          onChanged();
        } else {
          loginMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public proto.LoginMessageProto.LoginMessage.Builder getLoginMessageBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLoginMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      public proto.LoginMessageProto.LoginMessageOrBuilder getLoginMessageOrBuilder() {
        if (loginMessageBuilder_ != null) {
          return loginMessageBuilder_.getMessageOrBuilder();
        } else {
          return loginMessage_ == null ?
              proto.LoginMessageProto.LoginMessage.getDefaultInstance() : loginMessage_;
        }
      }
      /**
       * <code>optional .proto.LoginMessage loginMessage = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.LoginMessageProto.LoginMessage, proto.LoginMessageProto.LoginMessage.Builder, proto.LoginMessageProto.LoginMessageOrBuilder> 
          getLoginMessageFieldBuilder() {
        if (loginMessageBuilder_ == null) {
          loginMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.LoginMessageProto.LoginMessage, proto.LoginMessageProto.LoginMessage.Builder, proto.LoginMessageProto.LoginMessageOrBuilder>(
                  getLoginMessage(),
                  getParentForChildren(),
                  isClean());
          loginMessage_ = null;
        }
        return loginMessageBuilder_;
      }

      private java.util.List<proto.FriendListMessageProto.FriendListMessage> friendListMesage_ =
        java.util.Collections.emptyList();
      private void ensureFriendListMesageIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          friendListMesage_ = new java.util.ArrayList<proto.FriendListMessageProto.FriendListMessage>(friendListMesage_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.FriendListMessageProto.FriendListMessage, proto.FriendListMessageProto.FriendListMessage.Builder, proto.FriendListMessageProto.FriendListMessageOrBuilder> friendListMesageBuilder_;

      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public java.util.List<proto.FriendListMessageProto.FriendListMessage> getFriendListMesageList() {
        if (friendListMesageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friendListMesage_);
        } else {
          return friendListMesageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public int getFriendListMesageCount() {
        if (friendListMesageBuilder_ == null) {
          return friendListMesage_.size();
        } else {
          return friendListMesageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public proto.FriendListMessageProto.FriendListMessage getFriendListMesage(int index) {
        if (friendListMesageBuilder_ == null) {
          return friendListMesage_.get(index);
        } else {
          return friendListMesageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder setFriendListMesage(
          int index, proto.FriendListMessageProto.FriendListMessage value) {
        if (friendListMesageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendListMesageIsMutable();
          friendListMesage_.set(index, value);
          onChanged();
        } else {
          friendListMesageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder setFriendListMesage(
          int index, proto.FriendListMessageProto.FriendListMessage.Builder builderForValue) {
        if (friendListMesageBuilder_ == null) {
          ensureFriendListMesageIsMutable();
          friendListMesage_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendListMesageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder addFriendListMesage(proto.FriendListMessageProto.FriendListMessage value) {
        if (friendListMesageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendListMesageIsMutable();
          friendListMesage_.add(value);
          onChanged();
        } else {
          friendListMesageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder addFriendListMesage(
          int index, proto.FriendListMessageProto.FriendListMessage value) {
        if (friendListMesageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendListMesageIsMutable();
          friendListMesage_.add(index, value);
          onChanged();
        } else {
          friendListMesageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder addFriendListMesage(
          proto.FriendListMessageProto.FriendListMessage.Builder builderForValue) {
        if (friendListMesageBuilder_ == null) {
          ensureFriendListMesageIsMutable();
          friendListMesage_.add(builderForValue.build());
          onChanged();
        } else {
          friendListMesageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder addFriendListMesage(
          int index, proto.FriendListMessageProto.FriendListMessage.Builder builderForValue) {
        if (friendListMesageBuilder_ == null) {
          ensureFriendListMesageIsMutable();
          friendListMesage_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendListMesageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder addAllFriendListMesage(
          java.lang.Iterable<? extends proto.FriendListMessageProto.FriendListMessage> values) {
        if (friendListMesageBuilder_ == null) {
          ensureFriendListMesageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, friendListMesage_);
          onChanged();
        } else {
          friendListMesageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder clearFriendListMesage() {
        if (friendListMesageBuilder_ == null) {
          friendListMesage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          friendListMesageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public Builder removeFriendListMesage(int index) {
        if (friendListMesageBuilder_ == null) {
          ensureFriendListMesageIsMutable();
          friendListMesage_.remove(index);
          onChanged();
        } else {
          friendListMesageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public proto.FriendListMessageProto.FriendListMessage.Builder getFriendListMesageBuilder(
          int index) {
        return getFriendListMesageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public proto.FriendListMessageProto.FriendListMessageOrBuilder getFriendListMesageOrBuilder(
          int index) {
        if (friendListMesageBuilder_ == null) {
          return friendListMesage_.get(index);  } else {
          return friendListMesageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public java.util.List<? extends proto.FriendListMessageProto.FriendListMessageOrBuilder> 
           getFriendListMesageOrBuilderList() {
        if (friendListMesageBuilder_ != null) {
          return friendListMesageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friendListMesage_);
        }
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public proto.FriendListMessageProto.FriendListMessage.Builder addFriendListMesageBuilder() {
        return getFriendListMesageFieldBuilder().addBuilder(
            proto.FriendListMessageProto.FriendListMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public proto.FriendListMessageProto.FriendListMessage.Builder addFriendListMesageBuilder(
          int index) {
        return getFriendListMesageFieldBuilder().addBuilder(
            index, proto.FriendListMessageProto.FriendListMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.FriendListMessage friendListMesage = 4;</code>
       */
      public java.util.List<proto.FriendListMessageProto.FriendListMessage.Builder> 
           getFriendListMesageBuilderList() {
        return getFriendListMesageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.FriendListMessageProto.FriendListMessage, proto.FriendListMessageProto.FriendListMessage.Builder, proto.FriendListMessageProto.FriendListMessageOrBuilder> 
          getFriendListMesageFieldBuilder() {
        if (friendListMesageBuilder_ == null) {
          friendListMesageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.FriendListMessageProto.FriendListMessage, proto.FriendListMessageProto.FriendListMessage.Builder, proto.FriendListMessageProto.FriendListMessageOrBuilder>(
                  friendListMesage_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          friendListMesage_ = null;
        }
        return friendListMesageBuilder_;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 5;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string errorMessage = 5;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 5;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 5;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 5;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 5;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
    private static final proto.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.MessageProto.Message();
    }

    public static proto.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public proto.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/Message.proto\022\005proto\032\027proto/Chat" +
      "Message.proto\032\030proto/LoginMessage.proto\032" +
      "\035proto/FriendListMessage.proto\"\236\002\n\007Messa" +
      "ge\022!\n\004type\030\001 \002(\0162\023.proto.Message.Type\022\'\n" +
      "\013chatMessage\030\002 \003(\0132\022.proto.ChatMessage\022)" +
      "\n\014loginMessage\030\003 \001(\0132\023.proto.LoginMessag" +
      "e\0222\n\020friendListMesage\030\004 \003(\0132\030.proto.Frie" +
      "ndListMessage\022\024\n\014errorMessage\030\005 \001(\t\"R\n\004T" +
      "ype\022\020\n\014LoginMessage\020\000\022\017\n\013ChatMessage\020\001\022\025" +
      "\n\021FriendListMessage\020\002\022\020\n\014ErrorMessage\020\003B" +
      "\016B\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.ChatMessageProto.getDescriptor(),
          proto.LoginMessageProto.getDescriptor(),
          proto.FriendListMessageProto.getDescriptor(),
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "Type", "ChatMessage", "LoginMessage", "FriendListMesage", "ErrorMessage", });
    proto.ChatMessageProto.getDescriptor();
    proto.LoginMessageProto.getDescriptor();
    proto.FriendListMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
