#define SEMICOLON                        1
#define CREATE                           2
#define TABLE                            3
#define LEFTPARENTHESIS                  4
#define RIGHTPARENTHESIS                 5
#define COMMA                            6
#define INT_TYPE                         7
#define CHAR_TYPE                        8
#define INTEGER                          9
#define FLOAT_TYPE                      10
#define PRIMARY                         11
#define KEY                             12
#define UNIQUE                          13
#define NAME                            14
#define DROP                            15
#define WHERE                           16
#define DOT                             17
#define FLOAT                           18
#define NOT                             19
#define EQ                              20
#define NE                              21
#define LT                              22
#define GT                              23
#define LE                              24
#define GE                              25
#define AND                             26
#define OR                              27
#define SELECT                          28
#define FROM                            29
#define INSERT                          30
#define VALUES                          31
#define INTO                            32
#define STRING                          33
#define TIMES                           34
#define DELETE                          35
#define INDEX                           36
#define ON                              37
